import type { Metadata } from 'next';
import { LegalPage, H2, H3, P, UL, OL, Note } from '@/components/layout/LegalPage';

export const metadata: Metadata = {
  title: 'Vendor Terms Policy | Savidhi',
  description: 'Terms of business for spiritual service providers / vendors on Savidhi.',
};

export default function VendorTermsPage() {
  return (
    <LegalPage title="Vendor Terms — Spiritual Service Providers" lastUpdated="22nd Nov 2024">
      <P>
        This document is an electronic record per the Information Technology Act, 2000
        (&ldquo;IT Act, 2000&rdquo;), applicable rules, and provisions concerning electronic records
        in various statutes as amended by the IT Act, 2000. This electronic record is generated by a
        computer system and does not require physical or digital signatures.
      </P>
      <P>
        This document is published per Rule 3 (1) of the Information Technology (Intermediary
        Guidelines and Digital Media Ethics Code) Rules, 2021, requiring publication of rules,
        regulations, privacy policy, and Terms of Business for access to or usage of the Savidhi
        Platform.
      </P>
      <P>
        The Platform is owned and operated by VAIDIK VIKHYAT ASTRO PRIVATE LIMITED
        (&ldquo;Company&rdquo;), incorporated under the Companies Act, 2013.
      </P>
      <P>
        For Terms of Business purposes (&ldquo;ToB&rdquo;), &ldquo;you&rdquo; and &ldquo;your&rdquo;
        relate to any natural or legal person agreeing to become a Spiritual Service Provider /
        Vendor on the Platform. &ldquo;User&rdquo; means a Spiritual Service Provider / Vendor, and
        &ldquo;we&rdquo;, &ldquo;us&rdquo;, and &ldquo;our&rdquo; denote the Company.
      </P>
      <P>
        Your Platform use, feature access, and service provisioning are governed by executed
        agreements, these terms and conditions, applicable policies, notifications, and Platform
        communications incorporated herein by reference. Platform use constitutes contracting with
        the Company; these terms and policies represent binding obligations.
      </P>
      <P>
        The Company reserves the right to change, modify, add, or remove ToB portions any time.
        Material changes will be communicated via available modes. Continued Platform use following
        changes signifies acceptance.
      </P>
      <Note>
        ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT WITH ALL TERMS
        AND CONDITIONS UNDER THE TOB. PLEASE READ THE TOB CAREFULLY BEFORE PROCEEDING. By accepting
        the ToB, you accept and agree to be bound by all Company policies applicable to you, as
        amended periodically.
      </Note>

      <H2>Spiritual Service Provider / Vendor eligibility</H2>
      <P>
        Platform use is available only to persons capable of forming legally binding contracts under
        the Indian Contract Act, 1872. Persons &ldquo;incompetent to contract&rdquo; — including
        minors and un-discharged insolvents — are ineligible. If under 18 years, you shall not
        register, transact, or use the Platform. The Company reserves the right to terminate
        registration and refuse Platform access if you are discovered to be under 18. Registering as
        a legal entity represents that you are duly authorised by the business entity to accept the
        ToB and possess authority to bind the entity.
      </P>

      <H2>Your account and registration obligations</H2>
      <P>During Platform use, you agree to furnish requested details and information, including:</P>
      <UL>
        <li>Spiritual Service Provider / Vendor complete name</li>
        <li>Complete address</li>
        <li>Complete contact details — phone number and email address</li>
        <li>GSTIN (if available)</li>
        <li>PAN</li>
        <li>Pincode</li>
        <li>Pick-up address</li>
        <li>Registered address — principal geographic address of headquarters and all branches</li>
        <li>Bank account details</li>
        <li>Account holder name</li>
        <li>Cancelled cheque</li>
        <li>Signature</li>
        <li>Display legal name</li>
        <li>Legal name / trade name</li>
        <li>Contractual information (SLA)</li>
      </UL>
      <P>
        You agree that you possess necessary licences and permits for providing Spiritual Services,
        including those required by all applicable laws. &ldquo;Spiritual Services&rdquo; encompasses
        providing spiritual goods and services such as &lsquo;prasad&rsquo; and performing
        &lsquo;pooja&rsquo; on behalf of end customers.
      </P>
      <P>
        You remain responsible for maintaining information confidentiality and for any customer
        information shared pursuant to your engagement. You agree to maintain display name, login,
        and password confidentiality. If you provide untrue, inaccurate, not current, or incomplete
        information, the Company may suspend or terminate your account, indefinitely block Platform
        access, and terminate any arrangement.
      </P>

      <H2>Account deactivation</H2>
      <P>
        If a Spiritual Service Provider / Vendor requests account closure, the account will be held
        for 90 days ensuring smooth closure of prior transactions. This period allows downloading
        payment and taxation reports if required. After 90 days, the Vendor must confirm report
        downloading and request deactivation again. Upon confirmation, the account will be
        deactivated provided no outstanding Spiritual Services are due.
      </P>

      <H2>Communications</H2>
      <P>
        Using the Platform or sending emails, data, information, or communications to the Company or
        end customer means you communicate via electronic records and consent to periodic electronic
        record communications from the Company as required.
      </P>

      <H3>Consequently:</H3>
      <UL>
        <li>The Company does not determine, advise, control, or involve itself in offering or accepting Spiritual Service terms between you and customers.</li>
        <li>The Company makes no representations or warranties regarding product or Spiritual Service specifics (quality, value, saleability) proposed for sale or purchase. The Company does not implicitly or explicitly support or endorse any product or Spiritual Service.</li>
        <li>The Company bears no responsibility for any non-performance or contract breach between you and end customers, and is not required to mediate or resolve disputes.</li>
        <li>The Company makes no representations about user item-specifics (legal title, creditworthiness, identity, etc.). Verify any end customer&apos;s bona fides independently.</li>
        <li>The Company does not, during any transaction, take possession of products or services, gain title, or claim any rights over products or Spiritual Services offered.</li>
        <li>The Platform is solely a platform allowing you to reach a larger customer base. The Company merely provides communication platform services and acts as an intermediary between Vendors and end customers.</li>
      </UL>

      <H2>Use of the Platform</H2>
      <P>
        You understand that the Company and Platform merely provide hosting services to registered
        users. All advertised / listed items and contents constitute third-party user-generated
        content. The Company bears no responsibility or liability relating to or arising from such
        content. The Company neither originates nor modifies transmission information.
      </P>
      <P>
        You agree, undertake, and confirm that Platform use shall be strictly governed by binding
        principles. You shall not host, display, upload, modify, publish, transmit, update, or share
        any information or image, or perform Spiritual Services that:
      </P>
      <UL>
        <li>Belong to another person and over which you have no right.</li>
        <li>Are grossly harmful, harassing, blasphemous, defamatory, bigoted, obscene, pornographic, pedophilic, libelous, invasive of another&apos;s privacy, hateful, or racially / ethnically objectionable, encouraging money laundering or gambling, otherwise unlawful, or unlawfully threatening or harassing — including &lsquo;indecent representation of women&rsquo; per the Indecent Representation of Women (Prohibition) Act, 1986.</li>
        <li>Are false, inaccurate, or misleading.</li>
        <li>Are patently offensive — sexually explicit content or content promoting obscenity, pedophilia, racism, bigotry, hatred, or physical harm.</li>
        <li>Harass or advocate harassment of another person.</li>
        <li>Involve junk mail, chain letters, unsolicited mass mailing, or spamming.</li>
        <li>Promote illegal activity or conduct that is abusive, threatening, obscene, defamatory, or libelous.</li>
        <li>Infringe upon any third-party rights, including IP rights, privacy rights, or publicity rights.</li>
        <li>Promote illegal or unauthorised copies of another person&apos;s copyrighted work.</li>
        <li>Contain restricted or password-only access pages, hidden pages or images leading to other pages not linked to or from another accessible page.</li>
        <li>Provide material exploiting people sexually, violently, or otherwise inappropriately.</li>
        <li>Provide instructional information about illegal activities.</li>
        <li>Contain unauthorised videos, photographs, or images of another person (whether minor or adult).</li>
        <li>Attempt unauthorised Platform access or solicit passwords or personal identifying information for commercial or unlawful purposes.</li>
        <li>Engage in commercial activities and/or sales without prior written consent.</li>
        <li>Are illegal, interfere with another&apos;s use, harm minors, infringe IP, are fraudulent, deceive or impersonate.</li>
      </UL>
      <P>
        You shall not make negative, denigrating, or defamatory statements about the Company or its
        affiliates, or take actions imposing unreasonable infrastructure loads on the Platform.
      </P>
      <P>
        You may not use the Platform for unlawful purposes or to solicit illegal activity. You shall
        ensure full compliance with the IT Act, 2000 and all applicable laws.
      </P>
      <P>
        You shall not advertise or solicit other Vendors on the Platform to buy or sell products or
        services, or transmit chain letters / unsolicited commercial email. Misusing Platform
        information violates the ToB.
      </P>
      <Note>
        YOU REMAIN SOLELY RESPONSIBLE FOR POSTED MATERIAL CONTENT AND YOUR INDEPENDENT END CUSTOMER
        AND OTHER VENDOR COMMUNICATION, REGARDLESS OF FORM. Posted content does not reflect Company
        views.
      </Note>
      <P>Personal data shared with Vendors must be kept confidential and secure and deleted post-warranty period. Vendors shall not use customer data for unauthorised purposes.</P>

      <H2>Survival</H2>
      <P>Certain clauses, including indemnity, confidentiality, intellectual property, and dispute resolution, shall survive Agreement termination.</P>

      <H2>Indemnity</H2>
      <P>
        The Vendor agrees to indemnify and hold harmless the Company from any claims, losses,
        damages, costs, or expenses, including legal fees, arising due to Vendor obligation breach
        under this Agreement or Savidhi Policies.
      </P>

      <H2>Governing law and jurisdiction</H2>
      <P>
        This Agreement and any disputes arising under it shall be governed by Indian Laws, and courts
        having jurisdiction over the Company&apos;s registered office shall have exclusive
        jurisdiction.
      </P>

      <H2>Non-solicitation</H2>
      <P>
        The Vendor agrees not to solicit, directly or indirectly, Company customers, employees, or
        partners for their own or third-party businesses during the Agreement term and for 12 months
        after termination.
      </P>

      <H2>Intellectual property rights</H2>
      <P>
        All intellectual property related to the Company platform&apos;s data presentation,
        organisation, and arrangement is exclusively Company-owned. The Vendor shall not reproduce,
        copy, or use such intellectual property without prior written consent.
      </P>

      <H2>Non-assignability</H2>
      <P>
        The Vendor may not assign, delegate, or transfer rights or obligations under this Agreement
        without prior written Company approval. Any such attempt shall be deemed null and void.
      </P>

      <H2>Limited licence</H2>
      <P>
        The Company grants Spiritual Service Providers / Vendors a limited, non-transferable,
        non-exclusive, non-sublicensable, non-assignable, personal licence to use the Platform name
        and/or logo on Vendor invoices for Platform-concluded transactions.
      </P>

      <H2>Vendor payment</H2>
      <UL>
        <li>Transactions, transaction prices, and all commercial terms (delivery, product/service dispatch) are principal-to-principal bipartite contractual obligations between Vendors and end customers. The payment facility merely facilitates transaction completion. Use does not render the Company liable for non-delivery, non-receipt, non-payment, damage, warranty breach, or fraud.</li>
        <li>You authorise the Company or its service providers to collect, process, facilitate, and remit payments and/or transaction prices electronically or through other means to and from end customers. Your relationship with the Company is principal-to-principal. The Company is an independent contractor and does not control or assume Spiritual Services liability.</li>
        <li>You understand that the payment facility is neither banking nor a financial service, but merely a facilitator providing electronic, automated online payment facility for receiving payment, collection, and remittance for Platform transactions using existing authorised banking infrastructure and credit card payment gateway (PG) network.</li>
        <li>All valid bank account online transfers are processed using gateway support provided by the respective issuing bank.</li>
      </UL>

      <H2>Dispatch of products and / or services</H2>
      <UL>
        <li>You shall dispatch Spiritual Services for every transaction to end customers within stated time periods ensuring timely delivery.</li>
        <li>You shall provide dispatch details related to listed Spiritual Services in the manner and within the timeframe provided in policies. Failure to do so results in transaction cancellation.</li>
        <li>You shall dispatch Spiritual Services using only approved delivery channels providing appropriate &lsquo;proof of dispatch&rsquo; &amp; &lsquo;proof of delivery&rsquo; documentation or &lsquo;proof of service&rsquo;.</li>
        <li>Dispatch details shall be true, correct, duly authorised, and shall not be misleading, fraudulent, false, unauthorised, illegal, or contain misrepresentation.</li>
        <li>Failure to provide compliant dispatch details may lead to account suspension and/or termination.</li>
        <li>Transaction prices paid by end customers will be remitted to the Vendor&apos;s bank account contingent upon successfully providing relevant Spiritual Services along with &lsquo;proof of service&rsquo; and end customer receipt acknowledgment.</li>
      </UL>

      <H2>Vendor charges</H2>
      <UL>
        <li>Platform registration is free. The Company does not charge browsing or registration fees. However, for successful Spiritual Service bookings, the Company will charge platform fees from end customers per policies. The Company reserves the right to change fee policy any time. Unless otherwise stated, all fees are quoted in Indian Rupees (INR) and payable to the Company. You shall be solely responsible for all fee-payment law compliance.</li>
        <li>Vendors acknowledge that the Company will not be liable for damages, interests, or claims resulting from any delay or non-processing of transactions / transaction prices beyond Company control.</li>
        <li>The Company will collect payment on the Vendor&apos;s behalf. Once the Company has made bank account payments, it shall be discharged of any/all Vendor liabilities.</li>
      </UL>

      <H2>Compliance with laws</H2>
      <UL>
        <li>The Vendor undertakes compliance with all applicable laws and will sign captured declarations in this ToB.</li>
        <li>If you Process any Personal Information received from or on behalf of Company employees, contractors, users, partners, or other third parties (&ldquo;Company&apos;s Personal Information&rdquo;), you agree to comply with applicable data protection laws (including the IT Act, 2000 and the IT Rules, 2011), keep all Company&apos;s Personal Information in strict confidence, and Process it solely to fulfil your ToB obligations — never selling, renting, trading, leasing, or making unauthorised disclosure.</li>
        <li>If you provide your or others&apos; Personal Information to the Company for processing, you warrant such Information was lawfully collected and there is no Applicable Data Protection Law restriction. The Company will only use provided information per this ToB and its Privacy Policy.</li>
        <li>If your products / services are defective, deficient, adulterated, spurious, or lack advertised features, or are delivered late from the stated schedule, you shall provide refund, return / replacement, exchange, warranty &amp; guarantee, withdrawal, and cancellation benefits.</li>
      </UL>
      <P>You agree and undertake to:</P>
      <OL>
        <li>Register yourself with the Company for selling your Spiritual Services on the Platform.</li>
        <li>Display your details such as temple name and geographic address for listed Spiritual Services and other information.</li>
      </OL>
      <P>The Company shall be responsible for displaying your products / services details on the Platform, total prices &amp; breakup with all required charges (including delivery / postal / handling / conveyance charges, Platform fee and applicable taxes).</P>
      <P>You shall ensure your Spiritual Services&apos; authenticity or genuineness, and provide shipment and delivery updates on products / services shipped from your premises.</P>
    </LegalPage>
  );
}
