export const ROUTES = {
  HOME: '/',
  PUJA: '/puja',
  PUJA_DETAIL: (id: string) => `/puja/${id}`,
  PUJA_BOOKING: (id: string) => `/puja/${id}/book`,
  CHADHAVA: '/chadhava',
  CHADHAVA_DETAIL: (id: string) => `/chadhava/${id}`,
  TEMPLES: '/temples',
  TEMPLE_DETAIL: (id: string) => `/temples/${id}`,
  CONSULT: '/consult',
  ASTROLOGER_DETAIL: (id: string) => `/consult/${id}`,
  BOOK_APPOINTMENT: (id: string) => `/consult/${id}/book`,
  PANCHANG: '/panchang',
  POINTS: '/points',
  BOOKINGS: '/bookings',
  BOOKINGS_PUJA: '/bookings/puja',
  BOOKINGS_APPOINTMENTS: '/bookings/appointments',
  PUJA_STATUS: (id: string) => `/bookings/puja/${id}`,
  APPOINTMENT_STATUS: (id: string) => `/bookings/appointments/${id}`,
  PROFILE: '/profile',
  LOGIN: '/login',
} as const;
